exec:
	chmod +x *.py models/*.py tests/test_models/*.py

pycode:
	pycodestyle *.py

test_all:
	python3 -m unittest discover tests

test_base:
	python3 -m unittest tests/test_models/test_base.py

test_rectangle:
	python3 -m unittest tests/test_models/test_rectangle.py
